# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 19:49
from __future__ import unicode_literals

import bigbucketapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddedToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[(b'1', b'Dairy Product'), (b'2', b'Fruits'), (b'3', b'Vegetable'), (b'4', b'Grocery'), (b'5', b'Daily Utilies')], max_length=20)),
                ('sell_point', models.IntegerField()),
                ('city', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('longitude', models.FloatField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=bigbucketapp.models.products_saving_location)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(b'1', b'KISHAN'), (b'2', b'DUKHANDAAR'), (b'3', b'KARIDDAR')], max_length=11)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('village', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='products', to='bigbucketapp.UserDetail'),
        ),
        migrations.AddField(
            model_name='addedtocart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbucketapp.Product'),
        ),
        migrations.AddField(
            model_name='addedtocart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', related_query_name='cart_items', to='bigbucketapp.UserDetail'),
        ),
    ]
