# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 09:45
from __future__ import unicode_literals

import bigbucketapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_cart', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[(b'1', b'Dairy Product'), (b'2', b'Fruits'), (b'3', b'Vegetable'), (b'4', b'Grocery'), (b'5', b'Daily Utilies')], max_length=20)),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('city', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=bigbucketapp.models.products_saving_location)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('is_purchased', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(b'1', b'KISHAN'), (b'2', b'DUKHANDAAR'), (b'3', b'KARIDDAR')], max_length=11)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('village', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', related_query_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', related_query_name='purchased_items', to='bigbucketapp.UserDetail'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbucketapp.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='products', to='bigbucketapp.UserDetail'),
        ),
        migrations.AddField(
            model_name='addedtocart',
            name='future_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', related_query_name='cart_items', to='bigbucketapp.UserDetail'),
        ),
        migrations.AddField(
            model_name='addedtocart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbucketapp.Product'),
        ),
    ]
